import { PrismaClient, games } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // Inserting Players
  const playersData = [
    { //player_id:1
      first_name: 'Grayson',
      last_name: 'Callahan Shively',
      birthdate: new Date('2006-06-18'),
      height: 66,
      weight: 175,
      sex: 'Male',
      position: ['Pg', 'sg'],
      shirt_size: 'Medium',
    },
    {//player_id:2
      first_name: 'Tule',
      last_name: 'Edwards',
      birthdate: new Date('2008-01-31'),
      height: 76,
      weight: 150,
      sex: 'Male',
      position: ['W/F'],
      shirt_size: 'Large',
    },
    {––//player_id:3
      first_name: 'Ryan',
      last_name: 'Clark',
      birthdate: new Date('2004-03-05'),
      height: 73,
      weight: 170,
      sex: 'Male',
      position: ['SG', 'SF'],
      shirt_size: 'Large',
    },
    {––//player_id:4
      first_name: 'Brian',
      last_name: 'Fererro',
      birthdate: new Date('2006-09-28'),
      height: 72.5,
      weight: 200,
      sex: 'Male',
      position: ['SG', 'SF'],
      shirt_size: 'XL',
    },

    {//player_id:5
      first_name: 'Michael',
      last_name: 'Angelillo',
      birthdate: new Date('1989-08-18'),
      height: 73,
      weight: 330,
      sex: 'Male',
      position: ['SF'], // Michael's position is an array containing 'SF'
      shirt_size: 'XXXL', // Michael's shirt size is 'XXXL'
    },
    {//player_id:6
      first_name: 'Ben',
      last_name: 'Maselli',
      birthdate: new Date('1991-06-19'),
      height: 72,
      weight: 170,
      sex: 'Male',
      position: ['SF'], // Ben's position is an array containing 'SF'
      shirt_size: 'Large', // Ben's shirt size is 'Large'
    },

    {//player_id:7
      first_name: 'Chris',
      last_name: 'Wheeler',
      birthdate: new Date('1990-03-03'),
      height: 66,
      weight: 150,
      sex: 'Male',
      position: ['SG'], // Chris's position is an array containing 'SG'
      shirt_size: 'Medium', // Chris's shirt size is 'Medium'
    },

    {//player_id:8
      first_name: 'Louie',
      last_name: 'Costanzo',
      birthdate: new Date('1985-09-26'),
      height: 69,
      weight: 160,
      sex: 'Male',
      position: ['G'], // Louie's position is an array containing 'G'
      shirt_size: 'Medium', // Louie's shirt size is 'Medium'
    },
    {//player_id:9
      first_name: 'Chris',
      last_name: 'Mahurin',
      birthdate: new Date('1972-05-11'),
      height: 72,
      weight: 160,
      sex: 'Male',
      position: ['SG', 'SF'], // Chris's position is an array containing 'SG' and 'SF'
      shirt_size: 'Medium', // Chris's shirt size is 'Medium'
    },
    {//player_id:10
      first_name: 'Isaac',
      last_name: 'Van Etten',
      birthdate: new Date('1993-03-31'),
      height: 72,
      weight: 190,
      sex: 'Male',
      position: ['SG'], // Isaac's position is an array containing 'SG'
      shirt_size: 'Large', // Isaac's shirt size is 'Large'
    },
    {//player_id:11
      first_name: 'Jared',
      last_name: 'Brautigam',
      birthdate: new Date('1983-08-09'),
      height: 72,
      weight: 200,
      sex: 'Male',
      position: ['SG', 'PF', 'C'], // Jared's position is an array containing 'SG', 'PF', and 'C'
      shirt_size: 'XL', // Jared's shirt size is 'XL'
    },
    {//player_id:12
      first_name: 'Jeffrey',
      last_name: 'Tate',
      birthdate: new Date('1988-05-31'),
      height: 72,
      weight: 205,
      sex: 'Male',
      position: ['F/C'], // Jeffrey's position is an array containing 'F/C'
      shirt_size: 'Large', // Jeffrey's shirt size is 'Large'
    },
    {//player_id:13
      first_name: 'Gabriel',
      last_name: 'Beeson-McArdle',
      birthdate: new Date('1980-11-29'),
      height: 72,
      weight: 185,
      sex: 'Male',
      position: ['SG', 'SF'], // Gabriel's position is an array containing 'SG' and 'SF'
      shirt_size: 'XL', // Gabriel's shirt size is 'XL'
    },
    {//player_id:14
      first_name: 'John',
      last_name: 'Hoyt',
      birthdate: new Date('1988-06-25'),
      height: 73,
      weight: 240,
      sex: 'Male',
      position: [], // John's position is an empty array
      shirt_size: 'XXXL', // John's shirt size is 'XXXL'
    },
    {//player_id:15
      first_name: 'Kenny',
      last_name: 'G',
      birthdate: new Date('1984-08-30'),
      height: 67,
      weight: 160,
      sex: 'Male',
      position: ['PG'],
      shirt_size: 'Large',
    },
    {//player_id:16
      first_name: 'Michael',
      last_name: 'White',
      birthdate: new Date('1987-04-18'),
      height: 69,
      weight: 170,
      sex: 'Male',
      position: ['SF', 'SG'],
      shirt_size: 'Large',
    },
    {//player_id:17
      first_name: 'Iain',
      last_name: 'Dooly',
      birthdate: new Date('2002-05-28'),
      height: 73,
      weight: 170,
      sex: 'Male',
      position: ['PG', 'SG', 'SF'],
      shirt_size: 'Medium',
    },
    {//player_id:18
      first_name: 'Joshua',
      last_name: 'Fisher',
      birthdate: new Date('1982-11-18'),
      height: 72,
      weight: 220,
      sex: 'Male',
      position: ['PG', 'F', 'C'],
      shirt_size: 'XL',
    },
    {//player_id:19
      first_name: 'Tyler',
      last_name: 'Salcedo',
      birthdate: new Date('1991-06-12'),
      height: 79,
      weight: 165,
      sex: 'Male',
      position: ['PG'],
      shirt_size: 'Large',
    },
    {//player_id:20
      first_name: 'Gabriel',
      last_name: 'Ramirez',
      birthdate: new Date('1969-05-27'),
      height: 68,
      weight: 175,
      sex: 'Male',
      position: [],
      shirt_size: 'Large',
    },
    {//player_id:21
      first_name: 'Otis',
      last_name: "O'Toole",
      birthdate: new Date('1985-10-13'),
      height: 75,
      weight: 220,
      sex: 'Male',
      position: ['4', '5'],
      shirt_size: 'XXL',
    },
    {//player_id:22
      first_name: 'Nick',
      last_name: 'Barry',
      birthdate: new Date('1984-09-03'),
      height: 71,
      weight: 190,
      sex: 'Male',
      position: ['2', '1'],
      shirt_size: 'Large',
    },
    {//player_id:23
      first_name: 'Christian',
      last_name: 'Rotunno',
      birthdate: new Date('1988-11-13'),
      height: 71,
      weight: 185,
      sex: 'Male',
      position: ['G/F'],
      shirt_size: 'Large',
    },
    {//player_id:24
      first_name: 'Evan',
      last_name: 'Portier',
      birthdate: new Date('1988-08-22'),
      height: 69,
      weight: 165,
      sex: 'Male',
      position: ['G/F'],
      shirt_size: 'Medium',
    },
    {//player_id:25
      first_name: 'Tarzan',
      last_name: 'Couri',
      birthdate: new Date('1991-12-17'),
      height: 71,
      weight: 185,
      sex: 'Male',
      position: ['SF', 'PF'],
      shirt_size: 'Large',
    },
    {//player_id:26
      first_name: 'Arend',
      last_name: 'Hall',
      birthdate: new Date('1974-11-15'),
      height: 82,
      weight: 220,
      sex: 'Male',
      position: ['C', 'PF'],
      shirt_size: 'XL',
    },
    {//player_id:27
      first_name: 'Jarety',
      last_name: 'Michieli',
      birthdate: new Date('1992-02-07'),
      height: 70,
      weight: 170,
      sex: 'Male',
      position: ['XL'],
      shirt_size: 'XL',
    },
    {//player_id:28
      first_name: 'Eric',
      last_name: 'Andreson',
      birthdate: new Date('1992-04-15'),
      height: 70,
      weight: 170,
      sex: 'Male',
      position: ['PG', 'SG', 'SF'],
      shirt_size: 'Medium',
    },
    {//player_id:29
      first_name: 'Koppa',
      last_name: 'Enos',
      birthdate: new Date('1977-09-23'),
      height: 75,
      weight: 270,
      sex: 'Male',
      position: ['C', 'PF'],
      shirt_size: 'XXL',
    },

    {//player_id:30
      first_name: 'Tomas',
      last_name: 'Armijo',
      birthdate: new Date('2006-12-30'),
      height: 69,
      weight: 156.4,
      sex: 'Male',
      position: ['G'],
      shirt_size: 'Large',
    },
    {//player_id:31
      first_name: 'Dylan',
      last_name: 'Ramirez',
      birthdate: new Date('2008-06-24'),
      height: 68,
      weight: 135,
      sex: 'Male',
      position: [],
      shirt_size: 'Medium',
    },
    {//player_id:32
      first_name: 'Cadian',
      last_name: 'Ramirez',
      birthdate: new Date('2006-02-02'),
      height: 68,
      weight: 135,
      sex: 'Male',
      position: [],
      shirt_size: 'Medium',
    },
    {//player_id:33
      first_name: 'Miles',
      last_name: 'Allen',
      birthdate: new Date('2008-09-26'),
      height: 70,
      weight: 160,
      sex: 'Male',
      position: ['3', '4'],
      shirt_size: 'Medium',
    },
    {//player_id:34
      first_name: 'Owen',
      last_name: 'McIver',
      birthdate: new Date('2006-01-02'),
      height: 76,
      weight: 195,
      sex: 'Male',
      position: ['2', '3'],
      shirt_size: 'Large',
    },
    {//player_id:35
      first_name: 'Aiden',
      last_name: 'Panock',
      birthdate: new Date('2007-12-25'),
      height: 63,
      weight: 155,
      sex: 'Male',
      position: ['PG', 'SG'],
      shirt_size: 'Medium',
    },
    {//player_id:36
      first_name: 'Joom Koppa',
      last_name: 'Enos',
      birthdate: new Date('2006-07-19'),
      height: 73,
      weight: 268.2,
      sex: 'Male',
      position: ['PF', 'C'],
      shirt_size: 'XXL',
    },
    {//player_id:37
      first_name: 'Clayton',
      last_name: 'McNeely',
      birthdate: new Date('2008-09-16'),
      height: 71,
      weight: 157,
      sex: 'Male',
      position: ['G'],
      shirt_size: 'Large',
    },
  ];

  const teamsData = [
    { team_name: "Grayson's Guards", captain_id: 1, season_id: 1 },
    { team_name: "Tule 's Titans", captain_id: 2, season_id: 1 },
    { team_name: "Ryan's Wos Wangeles Wakers", captain_id: 3, season_id: 1 },
    { team_name: "Brian's Grass Valley Royals", captain_id: 4, season_id: 1 },
  ];
