import { PrismaClient, games } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // Inserting Players
  const playersData = [
    {
      first_name: 'Player',
      last_name: 'A1',
      birthdate: new Date('1990-01-01'),
      height: 70,
      weight: 180,
      sex: 'M',
      comment: 'Im the very best!',
    },
    {
      first_name: 'Player',
      last_name: 'A2',
      birthdate: new Date('1991-02-02'),
      height: 71,
      weight: 185,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'A3',
      birthdate: new Date('1992-03-03'),
      height: 72,
      weight: 190,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'A4',
      birthdate: new Date('1993-04-04'),
      height: 73,
      weight: 195,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'A5',
      birthdate: new Date('1994-05-05'),
      height: 74,
      weight: 200,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'A6',
      birthdate: new Date('1995-06-06'),
      height: 75,
      weight: 205,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'A7',
      birthdate: new Date('1996-07-07'),
      height: 76,
      weight: 210,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'A8',
      birthdate: new Date('1997-08-08'),
      height: 77,
      weight: 215,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'A9',
      birthdate: new Date('1998-09-09'),
      height: 118,
      weight: 420,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'B1',
      birthdate: new Date('1990-01-01'),
      height: 70,
      weight: 180,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'B2',
      birthdate: new Date('1991-02-02'),
      height: 71,
      weight: 185,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'B3',
      birthdate: new Date('1990-01-01'),
      height: 70,
      weight: 180,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'B4',
      birthdate: new Date('1991-02-02'),
      height: 71,
      weight: 185,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'B5',
      birthdate: new Date('1990-01-01'),
      height: 70,
      weight: 180,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'B6',
      birthdate: new Date('1991-02-02'),
      height: 71,
      weight: 185,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'B7',
      birthdate: new Date('1990-01-01'),
      height: 70,
      weight: 180,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'B8',
      birthdate: new Date('1991-02-02'),
      height: 71,
      weight: 185,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'B9',
      birthdate: new Date('1991-02-02'),
      height: 71,
      weight: 185,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'C1',
      birthdate: new Date('1990-01-01'),
      height: 70,
      weight: 180,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'C2',
      birthdate: new Date('1991-02-02'),
      height: 71,
      weight: 185,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'C3',
      birthdate: new Date('1992-03-03'),
      height: 72,
      weight: 190,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'C4',
      birthdate: new Date('1993-04-04'),
      height: 73,
      weight: 195,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'C5',
      birthdate: new Date('1994-05-05'),
      height: 74,
      weight: 200,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'C6',
      birthdate: new Date('1995-06-06'),
      height: 75,
      weight: 205,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'C7',
      birthdate: new Date('1996-07-07'),
      height: 76,
      weight: 210,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'C8',
      birthdate: new Date('1997-08-08'),
      height: 77,
      weight: 215,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'C9',
      birthdate: new Date('1998-09-09'),
      height: 118,
      weight: 420,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'D1',
      birthdate: new Date('1990-01-01'),
      height: 70,
      weight: 180,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'D2',
      birthdate: new Date('1991-02-02'),
      height: 71,
      weight: 185,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'D3',
      birthdate: new Date('1992-03-03'),
      height: 72,
      weight: 190,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'D4',
      birthdate: new Date('1993-04-04'),
      height: 73,
      weight: 195,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'D5',
      birthdate: new Date('1994-05-05'),
      height: 74,
      weight: 200,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'D6',
      birthdate: new Date('1995-06-06'),
      height: 75,
      weight: 205,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'D7',
      birthdate: new Date('1996-07-07'),
      height: 76,
      weight: 210,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'D8',
      birthdate: new Date('1997-08-08'),
      height: 77,
      weight: 215,
      sex: 'M',
      comment: 'Im the best!',
    },
    {
      first_name: 'Player',
      last_name: 'D9',
      birthdate: new Date('1998-09-09'),
      height: 118,
      weight: 420,
      sex: 'M',
      comment: 'Im the best!',
    },
  ];

  await prisma.players.createMany({ data: playersData });

  // Inserting a Season
  await prisma.seasons.create({ data: { start_date: new Date('2023-09-17') } });

  // Inserting Teams
  const teamsData = [
    { team_name: 'Team A', captain_id: 1, season_id: 1 },
    { team_name: 'Team B', captain_id: 10, season_id: 1 },
    { team_name: 'Team C', captain_id: 19, season_id: 1 },
    { team_name: 'Team D', captain_id: 28, season_id: 1 },
  ];

  await prisma.teams.createMany({ data: teamsData });

  // Associating Players with Teams
  const teamPlayersData = [
    { team_id: 1, player_id: 1 },
    { team_id: 1, player_id: 2 },
    { team_id: 1, player_id: 3 },
    { team_id: 1, player_id: 4 },
    { team_id: 1, player_id: 5 },
    { team_id: 1, player_id: 6 },
    { team_id: 1, player_id: 7 },
    { team_id: 1, player_id: 8 },
    { team_id: 1, player_id: 9 },
    { team_id: 2, player_id: 10 },
    { team_id: 2, player_id: 11 },
    { team_id: 2, player_id: 12 },
    { team_id: 2, player_id: 13 },
    { team_id: 2, player_id: 14 },
    { team_id: 2, player_id: 15 },
    { team_id: 2, player_id: 16 },
    { team_id: 2, player_id: 17 },
    { team_id: 2, player_id: 18 },
    { team_id: 3, player_id: 19 },
    { team_id: 3, player_id: 20 },
    { team_id: 3, player_id: 21 },
    { team_id: 3, player_id: 22 },
    { team_id: 3, player_id: 23 },
    { team_id: 3, player_id: 24 },
    { team_id: 3, player_id: 25 },
    { team_id: 3, player_id: 26 },
    { team_id: 3, player_id: 27 },
    { team_id: 4, player_id: 28 },
    { team_id: 4, player_id: 29 },
    { team_id: 4, player_id: 30 },
    { team_id: 4, player_id: 31 },
    { team_id: 4, player_id: 32 },
    { team_id: 4, player_id: 33 },
    { team_id: 4, player_id: 34 },
    { team_id: 4, player_id: 35 },
    { team_id: 4, player_id: 36 },
  ];

  await prisma.teamplayers.createMany({ data: teamPlayersData });

  // Inserting games for the first season
  const gamesData: games[] = [
    {
      id: 1,
      game_time: new Date('2023-09-20T18:30:00-07:00'),
      team_home_id: 1,
      team_away_id: 2,
      season_id: 1,
      home_score: 30,
      away_score: 40,
      location: 'Vets Hall',
    },
    {
      id: 2,
      game_time: new Date('2023-09-20T19:45:00-07:00'),
      team_home_id: 3,
      team_away_id: 4,
      season_id: 1,
      home_score: null,
      away_score: null,
      location: 'Vets Hall',
    },
    {
      id: 3,
      game_time: new Date('2023-09-27T18:30:00-07:00'),
      team_home_id: 1,
      team_away_id: 3,
      season_id: 1,
      home_score: null,
      away_score: null,
      location: 'Vets Hall',
    },
    {
      id: 4,
      game_time: new Date('2023-09-27T19:45:00-07:00'),
      team_home_id: 2,
      team_away_id: 4,
      season_id: 1,
      home_score: null,
      away_score: null,
      location: 'Vets Hall',
    },
    {
      id: 5,
      game_time: new Date('2023-10-04T18:30:00-07:00'),
      team_home_id: 1,
      team_away_id: 4,
      season_id: 1,
      home_score: null,
      away_score: null,
      location: 'Vets Hall',
    },
    {
      id: 6,
      game_time: new Date('2023-10-04T19:45:00-07:00'),
      team_home_id: 2,
      team_away_id: 3,
      season_id: 1,
      home_score: null,
      away_score: null,
      location: 'Vets Hall',
    },
    {
      id: 7,
      game_time: new Date('2023-10-11T18:30:00-07:00'),
      team_home_id: null,
      team_away_id: null,
      season_id: 1,
      home_score: null,
      away_score: null,
      location: 'Vets Hall',
    },
    {
      id: 8,
      game_time: new Date('2023-10-11T19:45:00-07:00'),
      team_home_id: null,
      team_away_id: null,
      season_id: 1,
      home_score: null,
      away_score: null,
      location: 'Vets Hall',
    },
    {
      id: 9,
      game_time: new Date('2023-10-18T18:30:00-07:00'),
      team_home_id: null,
      team_away_id: null,
      season_id: 1,
      home_score: null,
      away_score: null,
      location: 'Vets Hall',
    },
    {
      id: 10,
      game_time: new Date('2023-10-18T19:45:00-07:00'),
      team_home_id: null,
      team_away_id: null,
      season_id: 1,
      home_score: null,
      away_score: null,
      location: 'Vets Hall',
    },
  ];

  await prisma.games.createMany({ data: gamesData });

  // Insert PlayerStats
  const playerStatsData = [
    // PlayerStats for game_id = 1
    {
      player_id: 1,
      game_id: 1,
      home: true,
      twos_attempted: 10,
      twos_made: 5,
      minutes_played: 20,
      threes_attempted: 3,
      threes_made: 1,
      fouls: 2,
      assists: 3,
      blocks: 1,
      steals: 2,
      freethrows_attempted: 4,
      freethrows_made: 3,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 2,
      game_id: 1,
      home: true,
      twos_attempted: 8,
      twos_made: 4,
      minutes_played: 22,
      threes_attempted: 2,
      threes_made: 1,
      fouls: 1,
      assists: 4,
      blocks: 0,
      steals: 1,
      freethrows_attempted: 3,
      freethrows_made: 2,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 3,
      game_id: 1,
      home: true,
      twos_attempted: 10,
      twos_made: 5,
      minutes_played: 20,
      threes_attempted: 3,
      threes_made: 1,
      fouls: 2,
      assists: 3,
      blocks: 1,
      steals: 2,
      freethrows_attempted: 4,
      freethrows_made: 3,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 4,
      game_id: 1,
      home: true,
      twos_attempted: 8,
      twos_made: 4,
      minutes_played: 22,
      threes_attempted: 2,
      threes_made: 1,
      fouls: 1,
      assists: 4,
      blocks: 0,
      steals: 1,
      freethrows_attempted: 3,
      freethrows_made: 2,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 5,
      game_id: 1,
      home: true,
      twos_attempted: 10,
      twos_made: 5,
      minutes_played: 20,
      threes_attempted: 3,
      threes_made: 1,
      fouls: 2,
      assists: 3,
      blocks: 1,
      steals: 2,
      freethrows_attempted: 4,
      freethrows_made: 3,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 6,
      game_id: 1,
      home: true,
      twos_attempted: 8,
      twos_made: 4,
      minutes_played: 22,
      threes_attempted: 2,
      threes_made: 1,
      fouls: 1,
      assists: 4,
      blocks: 0,
      steals: 1,
      freethrows_attempted: 3,
      freethrows_made: 2,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 7,
      game_id: 1,
      home: true,
      twos_attempted: 10,
      twos_made: 5,
      minutes_played: 20,
      threes_attempted: 3,
      threes_made: 1,
      fouls: 2,
      assists: 3,
      blocks: 1,
      steals: 2,
      freethrows_attempted: 4,
      freethrows_made: 3,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 8,
      game_id: 1,
      home: true,
      twos_attempted: 8,
      twos_made: 4,
      minutes_played: 22,
      threes_attempted: 2,
      threes_made: 1,
      fouls: 1,
      assists: 4,
      blocks: 0,
      steals: 1,
      freethrows_attempted: 3,
      freethrows_made: 2,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 9,
      game_id: 1,
      home: true,
      twos_attempted: 10,
      twos_made: 5,
      minutes_played: 20,
      threes_attempted: 3,
      threes_made: 1,
      fouls: 2,
      assists: 3,
      blocks: 1,
      steals: 2,
      freethrows_attempted: 4,
      freethrows_made: 3,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 10,
      game_id: 1,
      home: false,
      twos_attempted: 8,
      twos_made: 4,
      minutes_played: 22,
      threes_attempted: 2,
      threes_made: 1,
      fouls: 1,
      assists: 4,
      blocks: 0,
      steals: 1,
      freethrows_attempted: 3,
      freethrows_made: 2,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 11,
      game_id: 1,
      home: false,
      twos_attempted: 10,
      twos_made: 5,
      minutes_played: 20,
      threes_attempted: 3,
      threes_made: 1,
      fouls: 2,
      assists: 3,
      blocks: 1,
      steals: 2,
      freethrows_attempted: 4,
      freethrows_made: 3,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 12,
      game_id: 1,
      home: false,
      twos_attempted: 8,
      twos_made: 4,
      minutes_played: 22,
      threes_attempted: 2,
      threes_made: 1,
      fouls: 1,
      assists: 4,
      blocks: 0,
      steals: 1,
      freethrows_attempted: 3,
      freethrows_made: 2,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 13,
      game_id: 1,
      home: false,
      twos_attempted: 10,
      twos_made: 5,
      minutes_played: 20,
      threes_attempted: 3,
      threes_made: 1,
      fouls: 2,
      assists: 3,
      blocks: 1,
      steals: 2,
      freethrows_attempted: 4,
      freethrows_made: 3,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 14,
      game_id: 1,
      home: false,
      twos_attempted: 8,
      twos_made: 4,
      minutes_played: 22,
      threes_attempted: 2,
      threes_made: 1,
      fouls: 1,
      assists: 4,
      blocks: 0,
      steals: 1,
      freethrows_attempted: 3,
      freethrows_made: 2,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 15,
      game_id: 1,
      home: false,
      twos_attempted: 10,
      twos_made: 5,
      minutes_played: 20,
      threes_attempted: 3,
      threes_made: 1,
      fouls: 2,
      assists: 3,
      blocks: 1,
      steals: 2,
      freethrows_attempted: 4,
      freethrows_made: 3,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 16,
      game_id: 1,
      home: false,
      twos_attempted: 8,
      twos_made: 4,
      minutes_played: 22,
      threes_attempted: 2,
      threes_made: 1,
      fouls: 1,
      assists: 4,
      blocks: 0,
      steals: 1,
      freethrows_attempted: 3,
      freethrows_made: 2,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 17,
      game_id: 1,
      home: false,
      twos_attempted: 7,
      twos_made: 3,
      minutes_played: 19,
      threes_attempted: 2,
      threes_made: 0,
      fouls: 3,
      assists: 4,
      blocks: 1,
      steals: 1,
      freethrows_attempted: 4,
      freethrows_made: 3,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 18,
      game_id: 1,
      home: false,
      twos_attempted: 10,
      twos_made: 6,
      minutes_played: 24,
      threes_attempted: 4,
      threes_made: 2,
      fouls: 1,
      assists: 2,
      blocks: 0,
      steals: 2,
      freethrows_attempted: 5,
      freethrows_made: 4,
    },

    // PlayerStats for game_id = 2
    {
      player_id: 19,
      game_id: 2,
      home: true,
      twos_attempted: 10,
      twos_made: 6,
      minutes_played: 20,
      threes_attempted: 3,
      threes_made: 1,
      fouls: 2,
      assists: 3,
      blocks: 1,
      steals: 2,
      freethrows_attempted: 4,
      freethrows_made: 3,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 20,
      game_id: 2,
      home: true,
      twos_attempted: 8,
      twos_made: 5,
      minutes_played: 22,
      threes_attempted: 2,
      threes_made: 1,
      fouls: 1,
      assists: 4,
      blocks: 0,
      steals: 1,
      freethrows_attempted: 3,
      freethrows_made: 2,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 21,
      game_id: 2,
      home: true,
      twos_attempted: 10,
      twos_made: 5,
      minutes_played: 20,
      threes_attempted: 3,
      threes_made: 1,
      fouls: 2,
      assists: 3,
      blocks: 1,
      steals: 2,
      freethrows_attempted: 4,
      freethrows_made: 3,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 22,
      game_id: 2,
      home: true,
      twos_attempted: 8,
      twos_made: 4,
      minutes_played: 22,
      threes_attempted: 2,
      threes_made: 1,
      fouls: 1,
      assists: 4,
      blocks: 0,
      steals: 1,
      freethrows_attempted: 3,
      freethrows_made: 2,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 23,
      game_id: 2,
      home: true,
      twos_attempted: 10,
      twos_made: 5,
      minutes_played: 20,
      threes_attempted: 3,
      threes_made: 1,
      fouls: 2,
      assists: 3,
      blocks: 1,
      steals: 2,
      freethrows_attempted: 4,
      freethrows_made: 3,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 24,
      game_id: 2,
      home: true,
      twos_attempted: 8,
      twos_made: 4,
      minutes_played: 22,
      threes_attempted: 2,
      threes_made: 1,
      fouls: 1,
      assists: 4,
      blocks: 0,
      steals: 1,
      freethrows_attempted: 3,
      freethrows_made: 2,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 25,
      game_id: 2,
      home: true,
      twos_attempted: 10,
      twos_made: 5,
      minutes_played: 20,
      threes_attempted: 3,
      threes_made: 1,
      fouls: 2,
      assists: 3,
      blocks: 1,
      steals: 2,
      freethrows_attempted: 4,
      freethrows_made: 3,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 26,
      game_id: 2,
      home: true,
      twos_attempted: 8,
      twos_made: 4,
      minutes_played: 22,
      threes_attempted: 2,
      threes_made: 1,
      fouls: 1,
      assists: 4,
      blocks: 0,
      steals: 1,
      freethrows_attempted: 3,
      freethrows_made: 2,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 27,
      game_id: 2,
      home: true,
      twos_attempted: 10,
      twos_made: 5,
      minutes_played: 20,
      threes_attempted: 3,
      threes_made: 1,
      fouls: 2,
      assists: 3,
      blocks: 1,
      steals: 2,
      freethrows_attempted: 4,
      freethrows_made: 3,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 28,
      game_id: 2,
      home: false,
      twos_attempted: 8,
      twos_made: 4,
      minutes_played: 22,
      threes_attempted: 2,
      threes_made: 1,
      fouls: 1,
      assists: 4,
      blocks: 0,
      steals: 1,
      freethrows_attempted: 3,
      freethrows_made: 2,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 29,
      game_id: 2,
      home: false,
      twos_attempted: 10,
      twos_made: 5,
      minutes_played: 20,
      threes_attempted: 3,
      threes_made: 1,
      fouls: 2,
      assists: 3,
      blocks: 1,
      steals: 2,
      freethrows_attempted: 4,
      freethrows_made: 3,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 30,
      game_id: 2,
      home: false,
      twos_attempted: 8,
      twos_made: 4,
      minutes_played: 22,
      threes_attempted: 2,
      threes_made: 1,
      fouls: 1,
      assists: 4,
      blocks: 0,
      steals: 1,
      freethrows_attempted: 3,
      freethrows_made: 2,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 31,
      game_id: 2,
      home: false,
      twos_attempted: 10,
      twos_made: 5,
      minutes_played: 20,
      threes_attempted: 3,
      threes_made: 1,
      fouls: 2,
      assists: 3,
      blocks: 1,
      steals: 2,
      freethrows_attempted: 4,
      freethrows_made: 3,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 32,
      game_id: 2,
      home: false,
      twos_attempted: 8,
      twos_made: 4,
      minutes_played: 22,
      threes_attempted: 2,
      threes_made: 1,
      fouls: 1,
      assists: 4,
      blocks: 0,
      steals: 1,
      freethrows_attempted: 3,
      freethrows_made: 2,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 33,
      game_id: 2,
      home: false,
      twos_attempted: 10,
      twos_made: 5,
      minutes_played: 20,
      threes_attempted: 3,
      threes_made: 1,
      fouls: 2,
      assists: 3,
      blocks: 1,
      steals: 2,
      freethrows_attempted: 4,
      freethrows_made: 3,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 34,
      game_id: 2,
      home: false,
      twos_attempted: 8,
      twos_made: 4,
      minutes_played: 22,
      threes_attempted: 2,
      threes_made: 1,
      fouls: 1,
      assists: 4,
      blocks: 0,
      steals: 1,
      freethrows_attempted: 3,
      freethrows_made: 2,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 35,
      game_id: 2,
      home: false,
      twos_attempted: 7,
      twos_made: 3,
      minutes_played: 19,
      threes_attempted: 2,
      threes_made: 0,
      fouls: 3,
      assists: 4,
      blocks: 1,
      steals: 1,
      freethrows_attempted: 4,
      freethrows_made: 3,
      offensive_rebounds: 3,
      defensive_rebounds: 4,
    },
    {
      player_id: 36,
      game_id: 2,
      home: false,
      twos_attempted: 10,
      twos_made: 6,
      minutes_played: 24,
      threes_attempted: 4,
      threes_made: 2,
      fouls: 1,
      assists: 2,
      blocks: 0,
      steals: 2,
      freethrows_attempted: 5,
      freethrows_made: 4,
    },
  ];

  await prisma.playerstats.createMany({ data: playerStatsData });

  // ... Continue adding data similarly for other models

  console.log('Data seeded!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
